# Generated by Django 5.1.4 on 2025-01-09 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
        ('doctor', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='appoinment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime'),
        ),
    ]
